# app/tools/rag/config.py
"""RAG 工具专属配置。从全局 app.config 导入 RAG 相关设置。"""
from app import config as _global

# 直接复用全局配置中的 RAG 参数
RAG_DEVICE = _global.RAG_DEVICE
RAG_USE_FP16 = _global.RAG_USE_FP16
RAG_BATCH_SIZE = _global.RAG_BATCH_SIZE
RAG_MAX_LENGTH = _global.RAG_MAX_LENGTH
RAG_RETRIEVAL_TOP_K = _global.RAG_RETRIEVAL_TOP_K
RAG_RETRIEVAL_MIN_SCORE = _global.RAG_RETRIEVAL_MIN_SCORE
RAG_POOLING = _global.RAG_POOLING
RAG_RERANKER_MAX_LENGTH = _global.RAG_RERANKER_MAX_LENGTH
RAG_EMBEDDING_MODEL = _global.RAG_EMBEDDING_MODEL
RAG_RERANKER_MODEL = _global.RAG_RERANKER_MODEL
