# Generated by Django 4.2 on 2026-05-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='会话ID')),
                ('user_input', models.TextField(verbose_name='用户输入')),
                ('ai_response', models.TextField(verbose_name='AI回复')),
                ('sentiment_score', models.FloatField(default=0.0, verbose_name='情感分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
            },
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('visitor_count', models.IntegerField(default=0, verbose_name='服务人次')),
                ('avg_sentiment', models.FloatField(default=0.0, verbose_name='平均满意度')),
                ('top_question', models.JSONField(default=list, verbose_name='热门问答')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
            },
        ),
        migrations.CreateModel(
            name='DigitalHumanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='形象名称')),
                ('avatar_url', models.URLField(verbose_name='形象地址')),
                ('voice_id', models.CharField(max_length=50, verbose_name='音色ID')),
                ('welcome_text', models.TextField(verbose_name='欢迎语')),
            ],
            options={
                'verbose_name': '数字人形象',
                'verbose_name_plural': '数字人形象',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('history', '历史典故'), ('nature', '自然风光'), ('faq', '常见问题'), ('route', '路线推荐')], max_length=20, verbose_name='分类')),
                ('embedding_vector', models.TextField(blank=True, null=True, verbose_name='向量字段(预留)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '知识库条目',
                'verbose_name_plural': '知识库条目',
            },
        ),
    ]
