# Generated by Django 4.2 on 2026-05-18

from django.db import migrations, models


def set_existing_indexed(apps, schema_editor):
    KnowledgeItem = apps.get_model('measureapp', 'KnowledgeItem')
    KnowledgeItem.objects.all().update(is_indexed=True)


def unset_existing_indexed(apps, schema_editor):
    KnowledgeItem = apps.get_model('measureapp', 'KnowledgeItem')
    KnowledgeItem.objects.all().update(is_indexed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('measureapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='is_indexed',
            field=models.BooleanField(default=False, verbose_name='是否入索引'),
        ),
        migrations.RunPython(set_existing_indexed, unset_existing_indexed),
    ]
