# Generated by Django 4.2 on 2026-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measureapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeitem',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='标题'),
        ),
    ]
