# Generated by Django 4.2 on 2026-05-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measureapp', '0002_alter_knowledgeitem_title'),
        ('measureapp', '0002_knowledgeitem_is_indexed'),
    ]

    operations = [
    ]
